package com.epam.papaya.rrmistarter;

import java.io.Serializable;

/**
 * @author Evgeny Borisov
 */

public interface AutoGeneratedController {
    default String getControllerPrefix() {
        return getClass().getInterfaces()[0].getSimpleName();
    }
}
